### ISSUE TITLE
Certain config files cause the Windows client to crash

### ISSUE THREAD

**Issue by kylefmohr** [andzeil/easy-mqtt-handler#1]
Hello! Very interested in this project as I've been looking for a decent MQTT GUI, and I know a little Python. 

It seems that something about my configuration file causes the application to crash, and it becomes completely unable to start again unless I delete the config files. I'll post the files here, it should be noted that I have since *revoked* the credentials found in the files, so I am sharing the username and password on purpose, in case they have something to do with it (length of password?)

I'll dig into the repo a little more this afternoon and submit a PR if I figure out what's causing this. 

P.S. I am adding .txt to the filenames just so that GitHub will let me attach them, the crashes are occurring while they're using their original filenames. 
[default-settings.json.txt](https://github.com/andzeil/easy-mqtt-handler/files/12795607/default-settings.json.txt)
[default-payloads.json.txt](https://github.com/andzeil/easy-mqtt-handler/files/12795608/default-payloads.json.txt)

**Comment by andzeil** [comment]
Hey @kylefmohr. Thanks for bringing this to my attention! I've debugged the issue and it boils down to having SSL/TLS enabled and not providing a server certificate file:

```
/.venv/bin/python ./src/easy_mqtt_handler/__main__.py 
Traceback (most recent call last):
  File "/./src/easy_mqtt_handler/util/MQTTWorkerThread.py", line 129, in run
    self.mqtt_connect()
  File "./src/easy_mqtt_handler/util/MQTTWorkerThread.py", line 210, in mqtt_connect
    self.client.tls_set(ca_certs=self.settings.server_certificate_file,
  File "./.venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 804, in tls_set
    context.load_verify_locations(ca_certs)
FileNotFoundError: [Errno 2] No such file or directory

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

There's actually two problems here:

1. There's currently no checks whether those files are really configured in the GUI and whether they exist on the filesystem at all. I've added these checks already and the tool is now loading your config and throwing an error onto the console on my local machine. I didn't push the change, yet (explanation below)

2. In contrast to what a browser does with HTTPs (getting the public certificate chain before connecting to the host), Easy MQTT Handler does no such thing right now, unfortunately. Maybe I should have made it more clear in the Readme.md file. What you could do is use openSSL on the command line to fetch the certificate chain, and create a file containing the needed certificates. In your case that would boil down to:

`openssl s_client -showcerts -connect broker.iot-analytics.cloudflarepubsub.com:8883`

Then create a file called e.g. **fullchain.pem** and copy the displayed certificates one after another into file. Each certificate starts with `-----BEGIN CERTIFICATE-----` and ends with `-----END CERTIFICATE-----`. Separate them with a single line break and save the file. Then provide it to Easy MQTT Handler as "Server Certificate / Certificate Chain" and it should connect. You can try to just use the fullchain.pem I've attached to this post. I've created it for you for **broker.iot-analytics.cloudflarepubsub.com:8883**. It should work fine.

Meanwhile give me some time to think about how the overall issue could be fixed best. I could just add some checks (mainly to prevent the tool from crashing) and a short paragraph in the Readme.md file and call it a day. However, I think it's maybe best to implement a sort of fallback for the scenario that the server certificate / certificate chain was not provided and try to fetch what's needed automatically ... you know: like users would probably expect, because it's usual using HTTPs.

I will keep you posted on my decision and the fix. For the moment I hope you can work around for some time.

BR

A. Zeil

[fullchain.zip](https://github.com/andzeil/easy-mqtt-handler/files/12796163/fullchain.zip)

**Comment by kylefmohr** [comment]
Got it! Thanks so much for the quick and thorough response, I was digging around crash dump files with no luck. I can certainly provide the cert in the meantime. 

Thanks again!

**Comment by andzeil** [comment]
If the user selects SSL/TLS (and doesn't provide a server certificate chain file) Easy MQTT Handler will now try to fetch the server certificate from the server automatically. If it fails to do so it will warn the user and ask them to provide certificates in a file. Besides that exception handling has been improved in this part of the code. This should prevent the Easy MQTT Handler from crashing if certificate and/or key files are not provided or do not exist. I will create a new release, soon. Closing this issue now.
